import { StoryStep } from './types';

export const crewStorySteps: StoryStep[] = [
  {
    id: 'crew-step-1',
    stepNumber: '01',
    category: 'CREW CREDENTIAL',
    categoryCode: 'PASS // 01',
    title: 'Create your official crew pass.',
    titleLead: 'Create your official',
    titleAccent: 'crew pass',
    titleTrail: '.',
    description: 'Showcase your experience and availability with one verified Aadhaar credential.',
    descriptionLead: 'Showcase your experience and availability with',
    descriptionHighlight: 'one verified Aadhaar credential',
    descriptionTrail: '— accepted across premier stadium and arena tours.',
    metaStamp: 'AADHAAR KYC: VERIFIED • ALL-ZONES',
    badge: 'Verified ID',
    keyPoints: [],
    ctaText: 'Issue My Crew Pass',
    visualType: 'crew-profile',
  },
  {
    id: 'crew-step-2',
    stepNumber: '02',
    category: 'STADIUM SHIFTS',
    categoryCode: 'SHIFT // 02',
    title: 'Browse high-paying shifts with locked daily escrow.',
    titleLead: 'Browse high-paying shifts with',
    titleAccent: 'locked daily escrow',
    titleTrail: '.',
    description: 'Explore stadium concerts and multi-day festivals with guaranteed daily compensation.',
    descriptionLead: 'Access stadium concerts and arena festivals with',
    descriptionHighlight: 'guaranteed daily compensation',
    descriptionTrail: 'held securely in advance.',
    metaStamp: 'ESCROW HELD • ₹3,500 – ₹8,000 / DAY',
    badge: 'Escrow Pay',
    keyPoints: [],
    ctaText: 'Explore Live Shifts',
    visualType: 'crew-discovery',
  },
  {
    id: 'crew-step-3',
    stepNumber: '03',
    category: 'SHIFT DIRECTORY',
    categoryCode: 'GEO // 03',
    title: 'Filter opportunities by city, role & payout.',
    titleLead: 'Filter opportunities by',
    titleAccent: 'city, role & payout',
    titleTrail: '.',
    description: 'Pinpoint gigs matching your schedule through instant geo-targeted matching.',
    descriptionLead: 'Pinpoint gigs matching your calendar with',
    descriptionHighlight: 'instant geo-targeted matching',
    descriptionTrail: 'across Mumbai, NCR, Bengaluru and Goa.',
    metaStamp: '142 ACTIVE METRO CALLS TODAY',
    badge: 'Instant Match',
    keyPoints: [],
    ctaText: 'Search Shift Board',
    visualType: 'crew-search',
  },
  {
    id: 'crew-step-4',
    stepNumber: '04',
    category: 'DISPATCH ENGINE',
    categoryCode: 'APP // 04',
    title: 'Submit in 1-click with pre-vetted credentials.',
    titleLead: 'Submit in 1-click with',
    titleAccent: 'pre-vetted credentials',
    titleTrail: '.',
    description: 'Your portfolio and attendance record are bundled automatically without paperwork.',
    descriptionLead: 'Your portfolio, gig history and punctuality score are',
    descriptionHighlight: 'bundled and verified automatically',
    descriptionTrail: 'without repetitive paperwork.',
    metaStamp: 'ZERO FORMS • 1-CLICK DOSSIER',
    badge: '1-Click Apply',
    keyPoints: [],
    ctaText: 'Apply With 1 Click',
    visualType: 'crew-apply',
  },
  {
    id: 'crew-step-5',
    stepNumber: '05',
    category: 'VENUE ENTRY',
    categoryCode: 'PASS // 05',
    title: 'Receive live digital passes & reporting call times.',
    titleLead: 'Receive live digital passes &',
    titleAccent: 'reporting call times',
    titleTrail: '.',
    description: 'Get your official venue badge with direct QR gate admission on arrival.',
    descriptionLead: 'Get your official venue badge with',
    descriptionHighlight: 'direct QR gate admission',
    descriptionTrail: ', briefing specs and supervisor contact on arrival.',
    metaStamp: 'GATE 4B • JIO WORLD CENTRE',
    badge: 'Live Pass',
    keyPoints: [],
    ctaText: 'Inspect Gate Pass',
    visualType: 'crew-track',
  },
  {
    id: 'crew-step-6',
    stepNumber: '06',
    category: 'FINANCIAL SETTLEMENT',
    categoryCode: 'PAY // 06',
    title: 'Earn same-day UPI payouts & verified 5-star ratings.',
    titleLead: 'Earn same-day UPI payouts &',
    titleAccent: 'verified ratings',
    titleTrail: '.',
    description: 'Receive instant post-shift UPI settlements with zero platform commission deductions.',
    descriptionLead: 'Receive',
    descriptionHighlight: 'instant post-shift UPI settlements',
    descriptionTrail: 'with zero deductions, building an unblemished event career record.',
    metaStamp: 'UPI SETTLEMENT: INSTANT • 0% FEES',
    badge: 'Instant UPI',
    keyPoints: [],
    ctaText: 'Join Verified Roster',
    visualType: 'crew-reputation',
  },
];

export const organiserStorySteps: StoryStep[] = [
  {
    id: 'org-step-1',
    stepNumber: '01',
    category: 'EVENT BLUEPRINT',
    categoryCode: 'PROD // 01',
    title: 'Publish production shifts in three minutes flat.',
    titleLead: 'Publish production shifts in',
    titleAccent: 'three minutes flat',
    titleTrail: '.',
    description: 'Deploy calls across staging, hospitality and entry gates with exact headcount allocation.',
    descriptionLead: 'Deploy calls across staging, hospitality and entry gates with',
    descriptionHighlight: 'exact headcount allocation',
    descriptionTrail: 'and shift guidelines.',
    metaStamp: 'DY PATIL STADIUM • 40 HEADCOUNT',
    badge: 'Fast Setup',
    keyPoints: [],
    ctaText: 'Build Event Blueprint',
    visualType: 'organiser-create',
  },
  {
    id: 'org-step-2',
    stepNumber: '02',
    category: 'CRITERIA SPEC',
    categoryCode: 'SPEC // 02',
    title: 'Lock role qualifications & escrow compensation.',
    titleLead: 'Lock role qualifications &',
    titleAccent: 'escrow compensation',
    titleTrail: '.',
    description: 'Specify dress codes, call times and secure daily compensation in escrow.',
    descriptionLead: 'Specify dress codes, call times and',
    descriptionHighlight: 'secure daily compensation in escrow',
    descriptionTrail: 'to attract top-tier event talent.',
    metaStamp: '100% ESCROW DEPOSIT VERIFIED',
    badge: 'Zero Risk',
    keyPoints: [],
    ctaText: 'Define Criteria',
    visualType: 'organiser-criteria',
  },
  {
    id: 'org-step-3',
    stepNumber: '03',
    category: 'TALENT DIRECTORY',
    categoryCode: 'POOL // 03',
    title: 'Access pre-screened crew without chaotic chats.',
    titleLead: 'Access pre-screened crew',
    titleAccent: 'without chaotic chats',
    titleTrail: '.',
    description: 'Tap into an active network of Aadhaar-verified event specialists with real track records.',
    descriptionLead: 'Tap into an active network of',
    descriptionHighlight: 'Aadhaar-verified event specialists',
    descriptionTrail: 'with verified shift records and punctuality scores.',
    metaStamp: '1,200+ VETTED PROFESSIONALS ACTIVE',
    badge: 'Vetted Pool',
    keyPoints: [],
    ctaText: 'Browse Crew Directory',
    visualType: 'organiser-discovery',
  },
  {
    id: 'org-step-4',
    stepNumber: '04',
    category: 'APPLICANT MATRIX',
    categoryCode: 'INBOX // 04',
    title: 'Evaluate candidates with 98%+ match scoring.',
    titleLead: 'Evaluate candidates with',
    titleAccent: '98%+ match scoring',
    titleTrail: '.',
    description: 'Review applications organized by verified past arena credits and punctuality.',
    descriptionLead: 'Review applications organized by',
    descriptionHighlight: 'verified past arena credits',
    descriptionTrail: ', attendance records and ratings in one clear view.',
    metaStamp: 'CANDIDATE DOSSIER • INSTANT COMPARISON',
    badge: 'Clean Inbox',
    keyPoints: [],
    ctaText: 'Review Applicants',
    visualType: 'organiser-inbox',
  },
  {
    id: 'org-step-5',
    stepNumber: '05',
    category: 'ROSTER LOCK',
    categoryCode: 'LOCK // 05',
    title: 'Confirm full rosters with automated agreements.',
    titleLead: 'Confirm full rosters with',
    titleAccent: 'automated agreements',
    titleTrail: '.',
    description: 'Digital terms, call times & venue passes dispatched with pre-vetted standbys on call.',
    descriptionLead: 'Issue confirmed assignments in one tap. Digital terms,',
    descriptionHighlight: 'call times & venue passes dispatched',
    descriptionTrail: 'with standby backup included.',
    metaStamp: '38 / 40 CONFIRMED • 4 STANDBYS ON CALL',
    badge: 'Auto Roster',
    keyPoints: [],
    ctaText: 'Lock Event Roster',
    visualType: 'organiser-shortlist',
  },
  {
    id: 'org-step-6',
    stepNumber: '06',
    category: 'LIVE ON-GROUND',
    categoryCode: 'WRAP // 06',
    title: 'Track live QR attendance & 1-tap escrow release.',
    titleLead: 'Track live QR attendance &',
    titleAccent: '1-tap escrow release',
    titleTrail: '.',
    description: 'Scan crew at turnstiles with zero dropouts guaranteed, and disburse UPI upon wrap.',
    descriptionLead: 'Scan crew at venue gates with',
    descriptionHighlight: 'zero dropouts guaranteed',
    descriptionTrail: ', and disburse UPI payments with one tap upon shift wrap.',
    metaStamp: '38/38 ATTENDANCE • ₹1.71L DISBURSED',
    badge: '0% Dropouts',
    keyPoints: [],
    ctaText: 'Hire Verified Crew',
    visualType: 'organiser-roster',
  },
];
