import { StoryStep } from './types';

export const crewStorySteps: StoryStep[] = [
  {
    id: 'crew-step-1',
    stepNumber: '01',
    category: 'CREW PASS',
    categoryCode: 'STEP // 01',
    title: 'Get your verified crew pass.',
    titleLead: 'Get your verified',
    titleAccent: 'crew pass',
    titleTrail: '.',
    description: 'Add your Aadhaar once. Get hired at top events.',
    descriptionLead: 'Add your Aadhaar once.',
    descriptionHighlight: 'Get hired at top events',
    descriptionTrail: 'without forms.',
    metaStamp: 'AADHAAR VERIFIED • ALL EVENTS',
    badge: 'Verified ID',
    keyPoints: [],
    ctaText: 'Get Crew Pass',
    visualType: 'crew-profile',
  },
  {
    id: 'crew-step-2',
    stepNumber: '02',
    category: 'DAILY PAY',
    categoryCode: 'PAY // 02',
    title: 'Find high-paying event shifts.',
    titleLead: 'Find high-paying',
    titleAccent: 'event shifts',
    titleTrail: '.',
    description: 'See concerts and festivals with money already saved in advance.',
    descriptionLead: 'See concerts and festivals with',
    descriptionHighlight: 'money saved in advance',
    descriptionTrail: 'for your pay.',
    metaStamp: 'ESCROW LOCKED • ₹3,500 – ₹8,000 / DAY',
    badge: 'Safe Pay',
    keyPoints: [],
    ctaText: 'See Open Shifts',
    visualType: 'crew-discovery',
  },
  {
    id: 'crew-step-3',
    stepNumber: '03',
    category: 'FIND WORK',
    categoryCode: 'JOBS // 03',
    title: 'Pick your city and role.',
    titleLead: 'Pick your city and',
    titleAccent: 'desired role',
    titleTrail: '.',
    description: 'Filter by city, dates, and payout. See gigs near you.',
    descriptionLead: 'Filter by city and dates.',
    descriptionHighlight: 'Find gigs near you',
    descriptionTrail: 'in seconds.',
    metaStamp: '140+ GIGS OPEN TODAY',
    badge: 'Quick Find',
    keyPoints: [],
    ctaText: 'Search Shifts',
    visualType: 'crew-search',
  },
  {
    id: 'crew-step-4',
    stepNumber: '04',
    category: '1-TAP APPLY',
    categoryCode: 'APPLY // 04',
    title: 'Apply with just 1 tap.',
    titleLead: 'Apply with just',
    titleAccent: '1 tap',
    titleTrail: '.',
    description: 'No forms to write. Your verified work history is sent instantly.',
    descriptionLead: 'No forms to write.',
    descriptionHighlight: 'Sent instantly',
    descriptionTrail: 'to the event manager.',
    metaStamp: 'ZERO FORMS • 1-TAP APPLY',
    badge: 'Instant Apply',
    keyPoints: [],
    ctaText: 'Apply in 1 Tap',
    visualType: 'crew-apply',
  },
  {
    id: 'crew-step-5',
    stepNumber: '05',
    category: 'GATE PASS',
    categoryCode: 'GATE // 05',
    title: 'Get your QR gate pass.',
    titleLead: 'Get your QR',
    titleAccent: 'gate pass',
    titleTrail: '.',
    description: 'Show your phone at the entry gate. Fast entry with zero delay.',
    descriptionLead: 'Show your phone at the gate.',
    descriptionHighlight: 'Fast QR entry',
    descriptionTrail: 'with shift time.',
    metaStamp: 'ENTRY PASS • READY ON PHONE',
    badge: 'Quick Entry',
    keyPoints: [],
    ctaText: 'View Gate Pass',
    visualType: 'crew-track',
  },
  {
    id: 'crew-step-6',
    stepNumber: '06',
    category: 'FAST PAYOUT',
    categoryCode: 'UPI // 06',
    title: 'Get paid right after your shift.',
    titleLead: 'Get paid right after',
    titleAccent: 'your shift',
    titleTrail: '.',
    description: 'Direct UPI payment into your bank. Zero commission cut.',
    descriptionLead: 'Direct UPI into your bank.',
    descriptionHighlight: 'Zero fees taken',
    descriptionTrail: 'from your pay.',
    metaStamp: 'INSTANT UPI • ZERO FEES',
    badge: 'Instant Pay',
    keyPoints: [],
    ctaText: 'Join as Crew',
    visualType: 'crew-reputation',
  },
];

export const organiserStorySteps: StoryStep[] = [
  {
    id: 'org-step-1',
    stepNumber: '01',
    category: 'POST SHIFT',
    categoryCode: 'POST // 01',
    title: 'Post event shifts in 2 minutes.',
    titleLead: 'Post event shifts in',
    titleAccent: '2 minutes',
    titleTrail: '.',
    description: 'Choose your date, crew count, and roles with zero paperwork.',
    descriptionLead: 'Choose date and crew count.',
    descriptionHighlight: 'Zero paperwork',
    descriptionTrail: 'needed.',
    metaStamp: 'FAST SETUP • 10 TO 100+ CREW',
    badge: 'Fast Post',
    keyPoints: [],
    ctaText: 'Post a Shift',
    visualType: 'organiser-create',
  },
  {
    id: 'org-step-2',
    stepNumber: '02',
    category: 'SAFE ESCROW',
    categoryCode: 'PAY // 02',
    title: 'Lock daily pay safely in escrow.',
    titleLead: 'Lock daily pay',
    titleAccent: 'safely in escrow',
    titleTrail: '.',
    description: 'Set call time and daily pay. Crew sees guaranteed money upfront.',
    descriptionLead: 'Set time and pay.',
    descriptionHighlight: 'Guaranteed pay',
    descriptionTrail: 'attracts top reliable crew.',
    metaStamp: '100% ESCROW PROTECTED',
    badge: 'Safe Escrow',
    keyPoints: [],
    ctaText: 'Set Shift Pay',
    visualType: 'organiser-criteria',
  },
  {
    id: 'org-step-3',
    stepNumber: '03',
    category: 'VERIFIED CREW',
    categoryCode: 'CREW // 03',
    title: 'Find ID-verified event staff.',
    titleLead: 'Find ID-verified',
    titleAccent: 'event staff',
    titleTrail: '.',
    description: 'No messy WhatsApp chats. Hire Aadhaar-checked crew with real ratings.',
    descriptionLead: 'No WhatsApp mess.',
    descriptionHighlight: 'Aadhaar-checked crew',
    descriptionTrail: 'ready to work.',
    metaStamp: '1,200+ CHECKED CREW',
    badge: 'Checked Crew',
    keyPoints: [],
    ctaText: 'Browse Crew',
    visualType: 'organiser-discovery',
  },
  {
    id: 'org-step-4',
    stepNumber: '04',
    category: 'EASY REVIEW',
    categoryCode: 'VIEW // 04',
    title: 'Pick the best candidates fast.',
    titleLead: 'Pick the best',
    titleAccent: 'candidates fast',
    titleTrail: '.',
    description: 'See past gigs, on-time score, and photos in one simple card.',
    descriptionLead: 'See past gigs and ratings.',
    descriptionHighlight: 'Pick in seconds',
    descriptionTrail: 'with zero calls.',
    metaStamp: 'CLEAN CARDS • FAST CHOICE',
    badge: 'Fast Pick',
    keyPoints: [],
    ctaText: 'See Applicants',
    visualType: 'organiser-inbox',
  },
  {
    id: 'org-step-5',
    stepNumber: '05',
    category: 'LOCK ROSTER',
    categoryCode: 'LOCK // 05',
    title: 'Confirm your crew in 1 click.',
    titleLead: 'Confirm your crew in',
    titleAccent: '1 click',
    titleTrail: '.',
    description: 'Passes and shift timings sent automatically with backup staff ready.',
    descriptionLead: 'One tap confirms everyone.',
    descriptionHighlight: 'Free backup staff',
    descriptionTrail: 'always included.',
    metaStamp: 'ROSTER LOCKED • BACKUPS READY',
    badge: 'Auto Roster',
    keyPoints: [],
    ctaText: 'Lock Roster',
    visualType: 'organiser-shortlist',
  },
  {
    id: 'org-step-6',
    stepNumber: '06',
    category: 'CHECK-IN & PAY',
    categoryCode: 'WRAP // 06',
    title: 'Scan QR entry and pay with 1 tap.',
    titleLead: 'Scan QR entry and',
    titleAccent: 'pay in 1 tap',
    titleTrail: '.',
    description: 'Scan crew at the gate. Release UPI payment in 1 tap when work finishes.',
    descriptionLead: 'Scan phone at gate.',
    descriptionHighlight: '1-tap UPI payout',
    descriptionTrail: 'when shift wraps.',
    metaStamp: 'ZERO NO-SHOWS • 1-TAP PAY',
    badge: '1-Tap Pay',
    keyPoints: [],
    ctaText: 'Hire Crew Now',
    visualType: 'organiser-roster',
  },
];
