import {
  CrewProfile,
  OrganiserProfile,
  AdminProfile,
  UserAccount,
  EventItem,
  CrewApplication,
  AppNotification,
  CREW_CATEGORIES,
  EVENT_TYPES,
  EventCoordinationGroup,
} from './types';

export { CREW_CATEGORIES, EVENT_TYPES };

export const INITIAL_CREW_PROFILES: CrewProfile[] = [
  {
    id: 'crew-sneha',
    name: 'Sneha Verma',
    phone: '+91 98111 22334',
    email: 'sneha.verma@gmail.com',
    experienceYears: 3,
    experienceLevel: 'Experienced',
    categories: ['Hospitality Staff', 'Registration Desk'],
    age: 24,
    gender: 'Female',
    address: 'Vesu Road, VIP Circle',
    pincode: '395007',
    city: 'Surat',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    systemRating: 4.9,
    reviewsCount: 18,
    completedEventsCount: 22,
    availability: 'Available',
    expectedPay: '₹1,500/day',
    bio: 'Experienced guest hospitality specialist and front-desk coordinator with 3+ years managing luxury wedding receptions.',
    profileCompletionPercentage: 100,
  },
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'evt-singhania-1',
    name: 'Grand Royal Rajputana Wedding',
    eventType: 'Wedding',
    date: '2026-11-15',
    startTime: '16:00',
    endTime: '23:30',
    venue: 'Avadh Utopia Luxury Lawns',
    fullAddress: 'Dumas Road, Surat, Gujarat 395007',
    city: 'Surat',
    expectedAttendance: 1200,
    organiserId: 'org-singhania',
    organiserName: 'Singhania Live Events',
    organiserEmail: 'singhania.events@gmail.com',
    crewPositionsTotal: 8,
    crewPositionsAvailable: 6,
    requiredCategory: 'Hospitality Staff',
    genderRequirement: 'Any',
    experienceRequirement: 'Experienced',
    dressCode: 'Black Formal Kurta / Suits',
    payAmount: 1800,
    payBasis: 'Per Shift',
    paymentMethod: 'Direct UPI / Bank Transfer',
    paymentTimeline: 'Same Day',
    advanceRequired: true,
    createdAt: '2026-09-01',
    status: 'Open',
  },
  {
    id: 'evt-rohan-1',
    name: 'Apex Music Fest & DJ Night',
    eventType: 'Concert',
    date: '2026-11-20',
    startTime: '17:00',
    endTime: '01:00',
    venue: 'Bandra Kurla Complex Arena',
    fullAddress: 'BKC, Mumbai, Maharashtra 400051',
    city: 'Mumbai',
    expectedAttendance: 3500,
    organiserId: 'org-rohan',
    organiserName: 'Apex Event Productions',
    organiserEmail: 'rohan.events@gmail.com',
    crewPositionsTotal: 12,
    crewPositionsAvailable: 10,
    requiredCategory: 'Support',
    genderRequirement: 'Any',
    experienceRequirement: 'Experienced',
    dressCode: 'All Black Crew Tee & Cargo',
    payAmount: 2200,
    payBasis: 'Per Shift',
    paymentMethod: 'Direct UPI / Bank Transfer',
    paymentTimeline: 'Within 24 Hours',
    advanceRequired: false,
    createdAt: '2026-09-05',
    status: 'Open',
  },
];

export const INITIAL_APPLICATIONS: CrewApplication[] = [
  {
    id: 'app-sneha-singhania',
    eventId: 'evt-singhania-1',
    eventName: 'Grand Royal Rajputana Wedding',
    eventDate: '2026-11-15',
    crewId: 'crew-sneha',
    crewName: 'Sneha Verma',
    crewEmail: 'sneha.verma@gmail.com',
    crewPhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    crewPhone: '+91 98111 22334',
    crewCategory: 'Hospitality Staff',
    experienceYears: 3,
    systemRating: 4.9,
    city: 'Surat',
    status: 'Pending',
    appliedAt: '2026-09-02',
    note: 'Specialized in VIP guest welcoming and hospitality management.',
  },
];

export const EMPTY_CREW_PROFILE: CrewProfile = {
  id: '',
  name: '',
  phone: '',
  email: '',
  experienceYears: 0,
  experienceLevel: 'Fresher',
  categories: [],
  age: 0,
  gender: 'Male',
  address: '',
  pincode: '',
  city: '',
  photoUrl: '',
  systemRating: 0,
  reviewsCount: 0,
  completedEventsCount: 0,
  availability: 'Available',
  expectedPay: '',
  bio: '',
  profileCompletionPercentage: 0,
};

export const EMPTY_ORGANISER_PROFILE: OrganiserProfile = {
  id: '',
  name: '',
  companyName: '',
  hasUdyam: false,
  udyamNumber: '',
  address: '',
  pincode: '',
  city: '',
  email: '',
  phone: '',
  photoUrl: '',
  activeEventsCount: 0,
};

export const INITIAL_ORGANISER_PROFILE: OrganiserProfile = {
  ...EMPTY_ORGANISER_PROFILE,
};

export const INITIAL_ADMIN_PROFILE: AdminProfile = {
  id: 'adm-1',
  name: 'Evencify Operations Admin',
  email: 'admin@evencify.com',
  role: 'admin',
  lastLogin: 'Today, 11:30 AM',
};

export const INITIAL_USERS: UserAccount[] = [
  {
    id: 'usr-admin',
    name: 'Evencify Operations Admin',
    email: 'admin@evencify.com',
    password: 'admin123',
    phone: '+91 98765 43210',
    role: 'admin',
    status: 'Active',
    city: 'Bengaluru',
    createdAt: '2026-08-01',
    verificationBadge: 'Platform Superadmin',
    isVerified: true,
  },
  {
    id: 'org-singhania',
    name: 'Rajesh Singhania',
    email: 'singhania.events@gmail.com',
    password: 'organiser123',
    phone: '+91 98250 11223',
    role: 'organiser',
    status: 'Active',
    city: 'Surat',
    createdAt: '2026-08-10',
    verificationBadge: 'Verified Organiser',
    isVerified: true,
  },
  {
    id: 'org-rohan',
    name: 'Rohan Mehta',
    email: 'rohan.events@gmail.com',
    password: 'organiser123',
    phone: '+91 98250 99887',
    role: 'organiser',
    status: 'Active',
    city: 'Mumbai',
    createdAt: '2026-08-15',
    verificationBadge: 'Verified Organiser',
    isVerified: true,
  },
  {
    id: 'crew-sneha',
    name: 'Sneha Verma',
    email: 'sneha.verma@gmail.com',
    password: 'crew123',
    phone: '+91 98111 22334',
    role: 'crew',
    status: 'Active',
    city: 'Surat',
    createdAt: '2026-08-20',
    verificationBadge: 'Top Rated Crew',
    isVerified: true,
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [];

export const INITIAL_EVENT_GROUPS: EventCoordinationGroup[] = [];
