import {
  CrewProfile,
  OrganiserProfile,
  AdminProfile,
  UserAccount,
  EventItem,
  CrewApplication,
  AppNotification,
  CREW_CATEGORIES,
  EVENT_TYPES,
  EventCoordinationGroup,
} from './types';

export { CREW_CATEGORIES, EVENT_TYPES };

export const INITIAL_CREW_PROFILES: CrewProfile[] = [
  {
    id: 'crew-1',
    name: 'Sneha Verma',
    phone: '+91 98251 44321',
    email: 'sneha.verma@example.com',
    experienceYears: 3,
    experienceLevel: 'Experienced',
    categories: ['Hospitality Staff', 'Registration Desk', 'Event Helper'],
    age: 23,
    gender: 'Female',
    address: '402, Riverfront Enclave, Vesu',
    pincode: '395007',
    city: 'Surat',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    systemRating: 4.9,
    reviewsCount: 26,
    completedEventsCount: 34,
    availability: 'Available for Upcoming Shifts',
    expectedPay: '₹1,500 / shift',
    bio: 'Experienced in VIP hospitality, guest registration desks, and crowd facilitation for luxury weddings and corporate summits.',
    profileCompletionPercentage: 90,
  },
  {
    id: 'crew-2',
    name: 'Rohan Mehta',
    phone: '+91 98790 12345',
    email: 'rohan.mehta@example.com',
    experienceYears: 4,
    experienceLevel: 'Experienced',
    categories: ['Setup / Teardown', 'Security', 'Event Helper'],
    age: 26,
    gender: 'Male',
    address: '88, Nilkanth Residency, Adajan',
    pincode: '395009',
    city: 'Surat',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    systemRating: 4.8,
    reviewsCount: 38,
    completedEventsCount: 52,
    availability: 'Immediate availability',
    expectedPay: '₹2,000 / day',
    bio: 'Disciplined stage setup lead with structural safety knowledge, stage trussing, and crowd safety management.',
    profileCompletionPercentage: 100,
  },
  {
    id: 'crew-3',
    name: 'Priya Choksi',
    phone: '+91 99044 87654',
    email: 'priya.choksi@example.com',
    experienceYears: 2,
    experienceLevel: 'Experienced',
    categories: ['Promoter', 'Registration Desk', 'Hospitality Staff'],
    age: 22,
    gender: 'Female',
    address: 'B-12, Green Palms, Piplod',
    pincode: '395007',
    city: 'Surat',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    systemRating: 4.9,
    reviewsCount: 19,
    completedEventsCount: 28,
    availability: 'Weekends & Evenings',
    expectedPay: '₹1,800 / shift',
    bio: 'Charismatic brand promoter fluent in Gujarati, Hindi, and English. Experienced with tech trade expos and corporate meets.',
    profileCompletionPercentage: 85,
  },
  {
    id: 'crew-4',
    name: 'Vikramaditya Rathore',
    phone: '+91 99099 33221',
    email: 'vikram.rathore@example.com',
    experienceYears: 5,
    experienceLevel: 'Veteran',
    categories: ['Security', 'Support'],
    age: 29,
    gender: 'Male',
    address: '14, Rajputana Colony, Katargam',
    pincode: '395004',
    city: 'Surat',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    systemRating: 5.0,
    reviewsCount: 44,
    completedEventsCount: 71,
    availability: 'Available on Booking',
    expectedPay: '₹3,000 / day',
    bio: 'Certified security coordinator. Trained in crisis de-escalation, crowd perimeter control and VIP protocol.',
    profileCompletionPercentage: 100,
  },
  {
    id: 'crew-5',
    name: 'Tanvi Joshi',
    phone: '+91 98240 55112',
    email: 'tanvi.j@example.com',
    experienceYears: 1,
    experienceLevel: 'Fresher',
    categories: ['Hospitality Staff', 'Registration Desk'],
    age: 20,
    gender: 'Female',
    address: '210, Shivalik Hills, Ghod Dod Road',
    pincode: '395001',
    city: 'Surat',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    systemRating: 4.7,
    reviewsCount: 8,
    completedEventsCount: 11,
    availability: 'Flexible timings',
    expectedPay: '₹1,200 / shift',
    bio: 'Enthusiastic hospitality talent eager to deliver exceptional guest satisfaction and warm ushering.',
    profileCompletionPercentage: 80,
  },
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'evt-101',
    name: 'Grand Wedding Celebration — Mehta & Desai',
    eventType: 'Wedding',
    date: '2026-10-20',
    startTime: '16:00',
    endTime: '23:30',
    venue: 'Avadh Utopia Luxury Resort, Dumas Road',
    city: 'Surat',
    expectedAttendance: 650,
    organiserId: 'org-1',
    organiserName: 'Singhania Events & Media',
    crewPositionsTotal: 2,
    crewPositionsAvailable: 0,
    requiredCategory: 'Hospitality Staff',
    genderRequirement: 'Any',
    ageRequirement: '20 - 30 years',
    experienceRequirement: 'Experienced',
    dressCode: 'Black formal trousers, crisp white shirt & black ethnic waistcoat',
    specialRequirements: 'Bilingual Gujarati & Hindi, guest escorting, VIP seating management.',
    payAmount: 1500,
    payBasis: 'Per Shift',
    paymentMethod: 'UPI Direct / Bank Transfer',
    paymentTimeline: 'Same Day',
    advanceRequired: false,
    createdAt: '2026-09-02',
    status: 'Open',
  },
  {
    id: 'evt-102',
    name: 'FinTech Leaders Summit 2026',
    eventType: 'Corporate',
    date: '2026-10-24',
    startTime: '08:00',
    endTime: '18:00',
    venue: 'Surat International Exhibition & Convention Centre (SIECC)',
    city: 'Surat',
    expectedAttendance: 1200,
    organiserId: 'org-1',
    organiserName: 'Singhania Events & Media',
    crewPositionsTotal: 16,
    crewPositionsAvailable: 5,
    requiredCategory: 'Registration Desk',
    genderRequirement: 'Any',
    ageRequirement: '21 - 28 years',
    experienceRequirement: 'Experienced',
    dressCode: 'Business formal dark blazers with white collared shirts',
    specialRequirements: 'QR badge scanner app proficiency, English fluency, welcome kit distribution.',
    payAmount: 2200,
    payBasis: 'Per Day',
    paymentMethod: 'Bank Transfer',
    paymentTimeline: 'Same Day',
    advanceRequired: false,
    createdAt: '2026-09-04',
    status: 'Open',
  },
  {
    id: 'evt-103',
    name: 'Sunburn Arena Live Concert',
    eventType: 'Concert',
    date: '2026-10-31',
    startTime: '15:00',
    endTime: '23:45',
    venue: 'VR Arena Ground, Dumas Road',
    city: 'Surat',
    expectedAttendance: 4500,
    organiserId: 'org-1',
    organiserName: 'Singhania Events & Media',
    crewPositionsTotal: 2,
    crewPositionsAvailable: 0,
    requiredCategory: 'Security',
    genderRequirement: 'Male',
    ageRequirement: '23 - 35 years',
    experienceRequirement: 'Experienced',
    dressCode: 'All-black tactical security polo, cargo pants, black boots',
    specialRequirements: 'Crowd barricade control, artist greenroom perimeter, wristband verification.',
    payAmount: 3000,
    payBasis: 'Per Shift',
    paymentMethod: 'UPI Direct',
    paymentTimeline: 'Same Day',
    advanceRequired: true,
    createdAt: '2026-09-06',
    status: 'Open',
  },
  {
    id: 'evt-104',
    name: 'Surat Sparkle Diamond & Jewellery Expo',
    eventType: 'Exhibition',
    date: '2026-11-05',
    startTime: '09:30',
    endTime: '19:00',
    venue: 'Surat Diamond Bourse Exhibition Hall',
    city: 'Surat',
    expectedAttendance: 8000,
    organiserId: 'org-1',
    organiserName: 'Singhania Events & Media',
    crewPositionsTotal: 30,
    crewPositionsAvailable: 14,
    requiredCategory: 'Promoter',
    genderRequirement: 'Female',
    ageRequirement: '20 - 28 years',
    experienceRequirement: 'Both',
    dressCode: 'Smart contemporary formal western attire / blazer',
    specialRequirements: 'High-ticket buyer greetings, catalogue walkthrough, multilingual fluency.',
    payAmount: 2500,
    payBasis: 'Per Day',
    paymentMethod: 'Bank Transfer',
    paymentTimeline: 'Within 24 Hours',
    advanceRequired: false,
    createdAt: '2026-09-08',
    status: 'Open',
  },
  {
    id: 'evt-105',
    name: 'Gujarat Tech & AI Developers Summit',
    eventType: 'Corporate',
    date: '2026-10-18',
    startTime: '09:00',
    endTime: '17:30',
    venue: 'Pandit Dindayal Upadhyay Indoor Stadium, Athwalines',
    fullAddress: 'Athwalines, Surat, Gujarat 395001',
    city: 'Surat',
    expectedAttendance: 1800,
    organiserId: 'org-1',
    organiserName: 'Singhania Events & Media',
    crewPositionsTotal: 12,
    crewPositionsAvailable: 6,
    requiredCategory: 'Registration Desk',
    genderRequirement: 'Any',
    ageRequirement: '20 - 30 years',
    experienceRequirement: 'Both',
    dressCode: 'Smart Casual / Tech Polo',
    specialRequirements: 'Badge printing assistance, speaker greenroom ushering.',
    payAmount: 1800,
    payBasis: 'Per Day',
    paymentMethod: 'Bank Transfer',
    paymentTimeline: 'Same Day',
    advanceRequired: false,
    createdAt: '2026-09-10',
    status: 'Open',
  },
  {
    id: 'evt-106',
    name: 'Vibrant Navratri Raas Garba Mahotsav',
    eventType: 'Festival',
    date: '2026-10-14',
    startTime: '19:30',
    endTime: '01:30',
    venue: 'Riverfront Event Grounds, Sabarmati',
    fullAddress: 'Sabarmati Riverfront Promenade, Ahmedabad, Gujarat 380009',
    city: 'Ahmedabad',
    expectedAttendance: 15000,
    organiserId: 'org-1',
    organiserName: 'Gujarat Heritage Planners',
    crewPositionsTotal: 40,
    crewPositionsAvailable: 18,
    requiredCategory: 'Security',
    genderRequirement: 'Any',
    ageRequirement: '21 - 35 years',
    experienceRequirement: 'Experienced',
    dressCode: 'Traditional Kurta / Dark Uniform',
    specialRequirements: 'Crowd management, VIP box coordination, entrance barcode verification.',
    payAmount: 2500,
    payBasis: 'Per Shift',
    paymentMethod: 'UPI Direct',
    paymentTimeline: 'Same Day',
    advanceRequired: true,
    createdAt: '2026-09-09',
    status: 'Open',
  },
  {
    id: 'evt-107',
    name: 'Bollywood Symphony Live with Arijit Singh',
    eventType: 'Concert',
    date: '2026-11-14',
    startTime: '18:00',
    endTime: '23:00',
    venue: 'Jio World Garden, Bandra Kurla Complex (BKC)',
    fullAddress: 'G Block, BKC, Bandra East, Mumbai, Maharashtra 400051',
    city: 'Mumbai',
    expectedAttendance: 12000,
    organiserId: 'org-1',
    organiserName: 'MegaStar Entertainment Mumbai',
    crewPositionsTotal: 60,
    crewPositionsAvailable: 24,
    requiredCategory: 'Hospitality Staff',
    genderRequirement: 'Any',
    ageRequirement: '20 - 30 years',
    experienceRequirement: 'Experienced',
    dressCode: 'Formal Black Suit / Blazer',
    specialRequirements: 'VIP lounge hospitality, artist escort, hospitality bar management.',
    payAmount: 3500,
    payBasis: 'Per Shift',
    paymentMethod: 'Bank Transfer',
    paymentTimeline: 'Same Day',
    advanceRequired: false,
    createdAt: '2026-09-11',
    status: 'Open',
  },
  {
    id: 'evt-108',
    name: 'Bengaluru Founders & Angel Investors Mixer',
    eventType: 'Corporate',
    date: '2026-10-22',
    startTime: '17:30',
    endTime: '21:30',
    venue: 'The Leela Palace Convention Hall, Old Airport Road',
    fullAddress: '23, HAL Old Airport Rd, Kodihalli, Bengaluru, Karnataka 560008',
    city: 'Bengaluru',
    expectedAttendance: 450,
    organiserId: 'org-1',
    organiserName: 'VentureSprint Network',
    crewPositionsTotal: 8,
    crewPositionsAvailable: 3,
    requiredCategory: 'Registration Desk',
    genderRequirement: 'Any',
    ageRequirement: '21 - 28 years',
    experienceRequirement: 'Both',
    dressCode: 'Business Formal',
    specialRequirements: 'Founder badge scanning, networking session timekeeping.',
    payAmount: 2000,
    payBasis: 'Per Shift',
    paymentMethod: 'UPI Direct',
    paymentTimeline: 'Same Day',
    advanceRequired: false,
    createdAt: '2026-09-12',
    status: 'Open',
  },
  {
    id: 'evt-109',
    name: 'Hands-on Professional Photography & Lighting Workshop',
    eventType: 'Other Event',
    date: '2026-10-25',
    startTime: '10:00',
    endTime: '17:00',
    venue: 'Sanjeev Kumar Auditorium Studio, Pal',
    fullAddress: 'Pal Gam, Surat, Gujarat 395009',
    city: 'Surat',
    expectedAttendance: 120,
    organiserId: 'org-1',
    organiserName: 'Visual Arts Academy Surat',
    crewPositionsTotal: 4,
    crewPositionsAvailable: 2,
    requiredCategory: 'Setup / Teardown',
    genderRequirement: 'Any',
    ageRequirement: '20 - 30 years',
    experienceRequirement: 'Fresher',
    dressCode: 'Comfortable dark studio attire',
    specialRequirements: 'Lighting reflector setup, equipment handling assistance.',
    payAmount: 1400,
    payBasis: 'Per Day',
    paymentMethod: 'UPI Direct',
    paymentTimeline: 'Same Day',
    advanceRequired: false,
    createdAt: '2026-09-12',
    status: 'Open',
  },
  {
    id: 'evt-110',
    name: 'India International Trade Fair & Industrial Expo',
    eventType: 'Exhibition',
    date: '2026-11-20',
    startTime: '10:00',
    endTime: '18:30',
    venue: 'Bharat Mandapam (IECC), Pragati Maidan',
    fullAddress: 'Pragati Maidan, New Delhi, Delhi 110001',
    city: 'Delhi',
    expectedAttendance: 25000,
    organiserId: 'org-1',
    organiserName: 'National Trade Promotion Forum',
    crewPositionsTotal: 80,
    crewPositionsAvailable: 35,
    requiredCategory: 'Promoter',
    genderRequirement: 'Any',
    ageRequirement: '20 - 32 years',
    experienceRequirement: 'Both',
    dressCode: 'Formal Navy Blazer with White Shirt',
    specialRequirements: 'International delegate assistance, brochure distribution.',
    payAmount: 2800,
    payBasis: 'Per Day',
    paymentMethod: 'Bank Transfer',
    paymentTimeline: 'Within 24 Hours',
    advanceRequired: false,
    createdAt: '2026-09-13',
    status: 'Open',
  },
  {
    id: 'evt-111',
    name: 'Vadodara Heritage Half Marathon 2026',
    eventType: 'Sports Event',
    date: '2026-11-08',
    startTime: '05:30',
    endTime: '11:30',
    venue: 'Laxmi Vilas Palace Gate Grounds',
    fullAddress: 'J.N. Marg, Vadodara, Gujarat 390001',
    city: 'Vadodara',
    expectedAttendance: 6000,
    organiserId: 'org-1',
    organiserName: 'Gujarat Marathon Association',
    crewPositionsTotal: 25,
    crewPositionsAvailable: 10,
    requiredCategory: 'Event Helper',
    genderRequirement: 'Any',
    ageRequirement: '18 - 30 years',
    experienceRequirement: 'Fresher',
    dressCode: 'Event branded volunteer t-shirt and sports shoes',
    specialRequirements: 'Hydration station distribution, runner medal distribution.',
    payAmount: 1200,
    payBasis: 'Per Shift',
    paymentMethod: 'UPI Direct',
    paymentTimeline: 'Same Day',
    advanceRequired: false,
    createdAt: '2026-09-13',
    status: 'Open',
  },
];

export const INITIAL_APPLICATIONS: CrewApplication[] = [
  {
    id: 'app-1',
    eventId: 'evt-101',
    crewId: 'crew-1',
    crewName: 'Sneha Verma',
    crewPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    crewPhone: '+91 98251 44321',
    crewCategory: 'Hospitality Staff',
    experienceYears: 3,
    systemRating: 4.9,
    city: 'Surat',
    status: 'Accepted',
    appliedAt: '2 days ago',
    note: 'Completed 3 luxury weddings with Singhania Events previously. Available for the full shift.',
  },
  {
    id: 'app-2',
    eventId: 'evt-101',
    crewId: 'crew-2',
    crewName: 'Rohan Patel',
    crewPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    crewPhone: '+91 98790 12345',
    crewCategory: 'Setup / Teardown',
    experienceYears: 4,
    systemRating: 4.8,
    city: 'Surat',
    status: 'Accepted',
    appliedAt: '1 day ago',
    note: 'Extensive background in stage light cues and artist console management for large weddings.',
  },
  {
    id: 'app-3',
    eventId: 'evt-102',
    crewId: 'crew-3',
    crewName: 'Priya Choksi',
    crewPhoto: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    crewPhone: '+91 99044 87654',
    crewCategory: 'Registration Desk',
    experienceYears: 2,
    systemRating: 4.9,
    city: 'Surat',
    status: 'Shortlisted',
    appliedAt: '1 day ago',
    note: 'Fluent in English and tech savvy with QR registration tools.',
  },
  {
    id: 'app-4',
    eventId: 'evt-102',
    crewId: 'crew-5',
    crewName: 'Kavita Joshi',
    crewPhoto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    crewPhone: '+91 97233 44556',
    crewCategory: 'Registration Desk',
    experienceYears: 3,
    systemRating: 4.8,
    city: 'Surat',
    status: 'Accepted',
    appliedAt: '2 days ago',
    note: 'Handled corporate badge scanning at Surat Diamond Bourse and Taj Gateway conventions.',
  },
  {
    id: 'app-5',
    eventId: 'evt-103',
    crewId: 'crew-4',
    crewName: 'Vikramaditya Rathore',
    crewPhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    crewPhone: '+91 99099 33221',
    crewCategory: 'Security',
    experienceYears: 5,
    systemRating: 5.0,
    city: 'Surat',
    status: 'Accepted',
    appliedAt: '3 hours ago',
    note: 'Head of security team with concert crowd management experience and first-aid certification.',
  },
  {
    id: 'app-6',
    eventId: 'evt-103',
    crewId: 'crew-6',
    crewName: 'Sameer Sheikh',
    crewPhoto: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
    crewPhone: '+91 98240 77889',
    crewCategory: 'Security',
    experienceYears: 3,
    systemRating: 4.7,
    city: 'Surat',
    status: 'Accepted',
    appliedAt: '4 hours ago',
    note: 'Bouncer and perimeter control crew member for major music festivals.',
  },
  {
    id: 'app-7',
    eventId: 'evt-104',
    crewId: 'crew-1',
    crewName: 'Sneha Verma',
    crewPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    crewPhone: '+91 98251 44321',
    crewCategory: 'Promoter',
    experienceYears: 3,
    systemRating: 4.9,
    city: 'Surat',
    status: 'Pending',
    appliedAt: '5 hours ago',
    note: 'Experience with luxury retail hospitality and high-net-worth VIP clientele in jewellery expos.',
  },
  {
    id: 'app-8',
    eventId: 'evt-104',
    crewId: 'crew-3',
    crewName: 'Priya Choksi',
    crewPhoto: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    crewPhone: '+91 99044 87654',
    crewCategory: 'Promoter',
    experienceYears: 2,
    systemRating: 4.9,
    city: 'Surat',
    status: 'Accepted',
    appliedAt: '1 day ago',
    note: 'Promoted diamond pavilion stalls during Surat International Expo 2025.',
  },
];

export const INITIAL_ORGANISER_PROFILE: OrganiserProfile = {
  id: 'org-1',
  name: 'Rajesh Singhania',
  companyName: 'Singhania Events & Media Ltd.',
  hasUdyam: true,
  udyamNumber: 'UDYAM-GJ-24-0098412',
  address: '601, World Trade Center, Ring Road',
  pincode: '395002',
  city: 'Surat',
  email: 'rajesh@singhaniaevents.com',
  phone: '+91 98251 10022',
  activeEventsCount: 4,
};

export const INITIAL_ADMIN_PROFILE: AdminProfile = {
  id: 'adm-1',
  name: 'Evencify Operations Admin',
  email: 'admin@evencify.com',
  role: 'admin',
  lastLogin: 'Today, 11:30 AM',
};

export const INITIAL_USERS: UserAccount[] = [
  {
    id: 'usr-1',
    name: 'Rajesh Singhania',
    email: 'rajesh@singhaniaevents.com',
    password: 'organiser123',
    phone: '+91 98251 10022',
    role: 'organiser',
    status: 'Active',
    city: 'Surat',
    createdAt: '2026-08-15',
    verificationBadge: 'Business Verified',
    isVerified: true,
    companyName: 'Singhania Events & Media Ltd.',
    hasUdyam: true,
    udyamNumber: 'UDYAM-GJ-24-0098412',
    address: '601, World Trade Center, Ring Road',
  },
  {
    id: 'usr-2',
    name: 'Sneha Verma',
    email: 'sneha.verma@example.com',
    password: 'crewpass123',
    phone: '+91 98251 44321',
    role: 'crew',
    status: 'Active',
    city: 'Surat',
    createdAt: '2026-08-20',
    verificationBadge: '4.9 ★ Crew Lead',
    isVerified: true,
    systemRating: 4.9,
    completedEventsCount: 14,
    expectedPay: '₹2,200 / shift',
    categories: ['Hospitality Staff', 'Registration Desk'],
  },
  {
    id: 'usr-3',
    name: 'Rohan Mehta',
    email: 'rohan.mehta@example.com',
    password: 'rohanpass123',
    phone: '+91 98790 12345',
    role: 'crew',
    status: 'Active',
    city: 'Surat',
    createdAt: '2026-08-22',
    verificationBadge: '4.8 ★ Crew Pro',
    isVerified: true,
    systemRating: 4.8,
    completedEventsCount: 8,
    expectedPay: '₹2,000 / shift',
    categories: ['Event Helper', 'Setup / Teardown'],
  },
  {
    id: 'usr-4',
    name: 'Vikramaditya Rathore',
    email: 'vikram.rathore@example.com',
    password: 'vikrampass123',
    phone: '+91 99099 33221',
    role: 'crew',
    status: 'Active',
    city: 'Surat',
    createdAt: '2026-08-25',
    verificationBadge: '5.0 ★ Security Specialist',
    isVerified: true,
    systemRating: 5.0,
    completedEventsCount: 22,
    expectedPay: '₹3,000 / shift',
    categories: ['Security', 'Support'],
  },
  {
    id: 'usr-5',
    name: 'Kavita Patel',
    email: 'kavita.patel@example.com',
    password: 'kavitapass123',
    phone: '+91 98240 55678',
    role: 'crew',
    status: 'Active',
    city: 'Surat',
    createdAt: '2026-09-02',
    verificationBadge: 'Pending Verification',
    isVerified: false,
    systemRating: 4.5,
    completedEventsCount: 2,
    expectedPay: '₹1,800 / shift',
    categories: ['Registration Desk', 'Promoter'],
  },
  {
    id: 'usr-admin',
    name: 'Evencify Operations Lead',
    email: 'admin@evencify.com',
    password: 'admin123',
    phone: '+91 98000 00001',
    role: 'admin',
    status: 'Active',
    city: 'Bengaluru',
    createdAt: '2026-08-01',
    verificationBadge: 'Platform Superadmin',
    isVerified: true,
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'New Crew Application Received',
    message: 'Sneha Verma applied for Hospitality Staff at "Grand Wedding Celebration".',
    time: '12m ago',
    type: 'application',
    read: false,
  },
  {
    id: 'notif-2',
    title: 'Application Shortlisted',
    message: 'Congratulations! You were shortlisted for "FinTech Leaders Summit 2026".',
    time: '1h ago',
    type: 'application',
    read: false,
  },
  {
    id: 'notif-3',
    title: 'Same-Day Shift Payment Released',
    message: '₹1,500 shift payout credited via UPI for yesterday\'s event.',
    time: '1d ago',
    type: 'payment',
    read: true,
  },
];

export const INITIAL_EVENT_GROUPS: EventCoordinationGroup[] = [
  {
    id: 'group-evt-101',
    eventId: 'evt-101',
    eventName: 'Grand Wedding Celebration — Mehta & Desai',
    eventDate: '2026-10-20',
    eventVenue: 'Avadh Utopia Luxury Resort, Dumas Road',
    organiserId: 'org-1',
    organiserName: 'Singhania Events & Media Ltd.',
    crewMembers: [
      {
        crewId: 'crew-1',
        crewName: 'Sneha Verma',
        crewPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
        crewCategory: 'Hospitality Staff',
        phone: '+91 98251 44321',
      },
      {
        crewId: 'crew-2',
        crewName: 'Rohan Patel',
        crewPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
        crewCategory: 'Setup / Teardown',
        phone: '+91 98790 12345',
      },
    ],
    createdByAdminId: 'adm-1',
    createdAt: '2026-09-12 14:30',
    status: 'active',
    messages: [
      {
        id: 'msg-1',
        groupId: 'group-evt-101',
        senderId: 'adm-1',
        senderName: 'Evencify Admin',
        senderRole: 'admin',
        content: 'Official Shift Coordination Group provisioned by Evencify Admin for "Grand Wedding Celebration — Mehta & Desai". All required positions (2/2) have been filled by accepted crew. Escrow is secured.',
        timestamp: 'Sep 12, 02:30 PM',
        isAnnouncement: true,
      },
      {
        id: 'msg-2',
        groupId: 'group-evt-101',
        senderId: 'org-1',
        senderName: 'Rajesh Singhania (Organiser)',
        senderRole: 'organiser',
        content: 'Welcome team! Please report directly to Banquet Hall 1 at Avadh Utopia by 15:30 sharp for briefing. Dress code is black formal trousers with crisp white shirts.',
        timestamp: 'Sep 12, 02:35 PM',
      },
      {
        id: 'msg-3',
        groupId: 'group-evt-101',
        senderId: 'crew-1',
        senderName: 'Sneha Verma',
        senderRole: 'crew',
        senderPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
        content: 'Noted sir! I have arrived in Surat and will reach the venue by 15:15 with full uniform.',
        timestamp: 'Sep 12, 02:40 PM',
      },
      {
        id: 'msg-4',
        groupId: 'group-evt-101',
        senderId: 'crew-2',
        senderName: 'Rohan Patel',
        senderRole: 'crew',
        senderPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
        content: 'Confirmed. Stage cues and lighting console checklist is prepared. See you tomorrow.',
        timestamp: 'Sep 12, 02:45 PM',
      },
    ],
  },
];

